blank_issues_enabled: false
contact_links:
Div:
{
Div1: carrot(#b675mh):
aliginet: red:
Giff alighened: all the colour are same in the project:

}
  - name: Ask a question or discuss a topic
  blank_issues_enabled: false
  link : all the procedder;
  // all the links are availabel in the different github:
  div red:
  {
    background: black;
    display: simple;
    distance: not mentioned;
    colour: difference between in the different colour;
    biometrics: not pera supported;
    alighent:  join yao;
    http: all the products in the different material:
    // all the products are availabel in the difference syptoms:
    All the productors
    
  }
  - name: Join Yao community:
  Http: All the products are the same in the previous project"""
  // All the material in the plateform:
  about: Join the community to get updates and news:
  
    url: https://discord.com/invite/BkMR2NUsjU
    about: Ask questions and discuss with other community members
  - name: Join Yao community
  - name: ask a question or discuss a topic::::



  // all the material in the plateform:
  
    url: https://yaoapps.com/community
    about: Join the community to get updates and news
